### PR TITLE
fix: claimed nfts in tx history

### LINKED ISSUE #8283: [Task]: When received funds from faucet, mana is not displayed in tx history until logout-login
### Task description

When received funds from faucet, mana is not displayed in tx history until logout-login
image
after logout and login
image

### LINKED ISSUE #8308: [Task]: Fix claimed collectibles are shown as sent and pending to claim
### Task description

Fix claimed collectibles are shown as sent and pending to claim

### PR DESCRIPTION
**Pull request by cpl121**
Closes #8308 
Closes #8283 

## Summary

> Please summarize your changes, describing **what** they are and **why** they were made.

...

## Changelog

```
- Please write a list of changes
```

### Platforms

> Please select any platforms where your changes have been tested.

-   **Desktop**
    -   [ ] MacOS
    -   [ ] Linux
    -   [ ] Windows

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to **test and verify** that your changes work as intended.

...

## Checklist

> Please tick the following boxes that are relevant to your changes.

-   [ ] I have followed the contribution guidelines for this project
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added or modified tests that prove my changes work as intended
-   [ ] I have verified that new and existing unit tests pass locally with my changes
-   [ ] I have verified that my latest changes pass CI workflows for testing and linting
-   [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by cpl121** [comment]
> everything seems to work fine except for one detail.. 🙈 when we send an NFT to an account and it's claimed by the receiving account, it's also being shown in the activity list of the sender as received. I think this is confusing... wdyt?
> 
> image

Nice catch! We can do this in another issue, wdyt?

**Comment by evavirseda** [comment]
> > everything seems to work fine except for one detail.. 🙈 when we send an NFT to an account and it's claimed by the receiving account, it's also being shown in the activity list of the sender as received. I think this is confusing... wdyt?
> > image
> 
> Nice catch! We can do this in another issue, wdyt?

sure!! in another issue it's ok :v:

**Review by evavirseda — APPROVED** [review]
all good, the previous comment will be fixed in another [issue](https://github.com/iotaledger/firefly/issues/8323) :rocket:

**Comment by marc2332** [comment]
> > everything seems to work fine except for one detail.. 🙈 when we send an NFT to an account and it's claimed by the receiving account, it's also being shown in the activity list of the sender as received. I think this is confusing... wdyt?
> > image
> 
> Nice catch! We can do this in another issue, wdyt?

This wasnt happening before tho

**Review by marc2332 — APPROVED** [review]

**Pull request merged**
