### PR TITLE
feat: update wallet.rs dependency

### PR DESCRIPTION
**Pull request by Tuditi**
## Summary

Updated @iota/wallet package to latest

Changelog Wallet.rs: 
```
- Call `try_get_outputs_metadata` instead of `try_get_outputs` when possible (more efficient)
- Min storage deposit amount in `prepare_output()` with expiration unlock condition
- NFT id in `prepare_output()` when the NFT output still has the null id
- Don't require address approval on ledger nano during account recovery.
- Updated dependencies
- Add getIncomingTransactionData() and IncomingTransactionData type.
- Improve output consolidation logic.
- Improve syncing
- Added participation methods
- Fix for local time issue
```

## Changelog

```
- Updated @iota/wallet package to 2.0.3-rc.8
```

## Relevant Issues

closes: #5219 
...

### Platforms

> Please select any platforms where your changes have been tested.

- __Desktop__
  - [ ] MacOS
  - [x] Linux
  - [ ] Windows
- __Mobile__
  - [ ] iOS
  - [ ] Android

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to __test and verify__ that your changes work as intended.

...

## Checklist

> Please tick all of the following boxes that are relevant to your changes.

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or modified tests that prove my changes work as intended
- [ ] I have verified that new and existing unit tests pass locally with my changes
- [ ] I have verified that my latest changes pass CI workflows for testing and linting
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by nicole-obrien — CHANGES_REQUESTED** [review]
Introduces a new bug when sending an NFT that you have minted

**Review by nicole-obrien — CHANGES_REQUESTED** [review]
Unable to build the latest:
```
error /Users/nicoleobrien/repos/if/firefly-stardust/node_modules/@iota/wallet: Command failed.
Exit code: 101
Command: prebuild-install --runtime napi --tag-prefix nodejs-binding-v || npm run rebuild
Arguments: 
Directory: /Users/nicoleobrien/repos/if/firefly-stardust/node_modules/@iota/wallet
Output:
prebuild-install warn install No prebuilt binaries found (target=6 runtime=napi arch=arm64 libc= platform=darwin)

> @iota/wallet@2.0.3-rc.6 rebuild
> node scripts/neon-build && tsc && node scripts/strip.js


> @iota/wallet@2.0.3-rc.6 build:neon
> cargo-cp-artifact -nc ./index.node -- cargo build --release --message-format=json-render-diagnostics

    Updating git repository `https://github.com/iotaledger/wallet.rs`
    Updating git repository `https://github.com/iotaledger/iota.rs`
    Updating crates.io index
error: failed to select a version for `iota-wallet`.
    ... required by package `wallet v0.2.0 (/Users/nicoleobrien/repos/if/firefly-stardust/node_modules/@iota/wallet)`
versions that meet the requirements `*` are: 0.15.2

the package `wallet` depends on `iota-wallet`, with features: `events` but `iota-wallet` does not have these features.
```

**Comment by MarkNerdi** [comment]
> Unable to build the latest:

for me it correctly uses the prebuilds when building

**Review by nicole-obrien — APPROVED** [review]
LGTM!

**Pull request merged**
