### PR TITLE
feat: change node url for proposal

### PR DESCRIPTION
**Pull request by MarkNerdi**
## Summary

> Please summarize your changes, describing **what** they are and **why** they were made.

...

## Changelog

```
- Please write a list of changes
```

### Platforms

> Please select any platforms where your changes have been tested.

-   **Desktop**
    -   [ ] MacOS
    -   [ ] Linux
    -   [ ] Windows
-   **Mobile**
    -   [ ] iOS
    -   [ ] Android

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to **test and verify** that your changes work as intended.

...

## Checklist

> Please tick the following boxes that are relevant to your changes.

-   [ ] I have followed the contribution guidelines for this project
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added or modified tests that prove my changes work as intended
-   [ ] I have verified that new and existing unit tests pass locally with my changes
-   [ ] I have verified that my latest changes pass CI workflows for testing and linting
-   [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by maxwellmattryan — CHANGES_REQUESTED** [review]
Have one requested change with some feedback:
- When I change the node URL, it isn't reactive in the `ProposalInformationPane`

**Comment by maxwellmattryan** [comment]
I didn't notice this the last time I tested this PR, but we should adjust the locales when editing a proposal to something like "Successfully edited proposal" instead of "Proposal successfully added"

**Review by maxwellmattryan — DISMISSED** [review]
Code LGTM! Just have one last thing we should do before merging in :pray:

**Comment by nicole-obrien** [comment]
Dropdown is hidden on the popup

Screenshot 2023-02-24 at 10 03 17

**Review by nicole-obrien — APPROVED** [review]
LGTM!

**Pull request merged**
