### PR TITLE
chore: update mobile icon assets

### PR DESCRIPTION
**Pull request by kraftjs**
## Summary

> Please summarize your changes, describing **what** they are and **why** they were made.

Update mobile v2 icons to use Firefly v2 designs for both mobile app icon and mobile splash screen.

## Changelog

```
- Deleted unused / redundant icons and shellscript from packages/mobile/icons
- Updated assetgen.sh to reflect folder name changes and improved imagemagick convert arguments
- Updated ios icons and renamed folder to packages/mobile/capacitor/assets/ios
- Updated android icons and renamed folder to packages/mobile/capacitor/assets/android
- Updated splash screen icons and renamed folder to packages/mobile/capacitor/assets/splash
```

### Platforms

> Please select any platforms where your changes have been tested.

-   **Desktop**
    -   [ ] MacOS
    -   [ ] Linux
    -   [ ] Windows
-   **Mobile**
    -   [x] iOS
    -   [x] Android

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to **test and verify** that your changes work as intended.

I've tested all of this locally, but ensure app icons are working for Android and iOS across different stages. Also make sure splash screen appears correctly.

## Checklist

> Please tick the following boxes that are relevant to your changes.

-   [x] I have followed the contribution guidelines for this project
-   [x] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added or modified tests that prove my changes work as intended
-   [ ] I have verified that new and existing unit tests pass locally with my changes
-   [ ] I have verified that my latest changes pass CI workflows for testing and linting
-   [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by jeeanribeiro — CHANGES_REQUESTED** [review]
iOS icon appearance looks good in all variants

Android icon looks very small compared to other apps and the previous Firefly version

**Comment by kraftjs** [comment]
> iOS icon appearance looks good in all variants
> 
> Android icon looks very small compared to other apps and the previous Firefly version

I think it looks smaller than it is on the android simulator because the simulator's background screen color is the same color as the app icon's background. I moved it to the lighter part of the simulator in the attached photo to better showcase the icon. We also talked about the previous Firefly Icon being too large on Android and not looking right, so it needs to be smaller than the original icon was. We can bring it up in the sync and get some input from the others.

**Comment by kraftjs** [comment]
Newest android icon size:

**Review by jeeanribeiro — APPROVED** [review]
LGTM, nice job ✅

**Pull request merged**
