### PR TITLE
chore: change header animation

### LINKED ISSUE #3703: [Task]: Adjust content lift
### Task description

TBD

### Requirements

- [ ] Background fade is still visible when the content is lifted up
- [ ] Buttons do not scale 

### Acceptance criteria

Can be closed when all requirements are complete

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

### LINKED ISSUE #3752: [Task]: Remove balance precision toggle if we keep `mobileHeaderAnimation`
### Task description

Balance precision toggle collides with the header animation
image

### Requirements

TBD

### Acceptance criteria

TBD

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

### PR DESCRIPTION
**Pull request by paul-boegelsack**
## Summary

This PR changes the animation when the user swipes to scroll the content. Top navigation is no longer affected, so removing balance precision isn't necessary.

## Changelog

```
- Removed mobile header animation from AccountNavigation, MainMenu and Dashboard
- Changed the animations behaviour in the AccountBalance and refactored the code
- Background fade now moves up and down as well
```

## Relevant Issues

Closes #3752 
Closes #3703

## Testing

Swipe the content (asset or activity list)

### Platforms

> Please select any platforms where your changes have been tested.

- __Desktop__
  - [ ] MacOS
  - [ ] Linux
  - [ ] Windows
- __Mobile__
  - [x] iOS
  - [x] Android

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to __test and verify__ that your changes work as intended.

...

## Checklist

> Please tick all of the following boxes that are relevant to your changes.

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or modified tests that prove my changes work as intended
- [ ] I have verified that new and existing unit tests pass locally with my changes
- [ ] I have verified that my latest changes pass CI workflows for testing and linting
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by begonaalvarezd — APPROVED** [review]
it works 🚀 very nice work 💪🏼

**Review by begonaalvarezd — CHANGES_REQUESTED** [review]
just realized it has conflicts with base 🙏🏼 we should fix that first

**Review by begonaalvarezd — APPROVED** [review]
synced with base and accepting 👍🏼

**Comment by paul-boegelsack** [comment]
> synced with base and accepting 👍🏼

Awesome, thank you for your help! 👍

**Pull request merged**
