### PR TITLE
fix: truncate long tx metadata

### PR DESCRIPTION
**Pull request by jeeanribeiro**
## Summary
Adds margin right to key text and truncate to value text in KeyValueBox

### Platforms
- __Desktop__
  - [ ] MacOS
  - [x] Linux
  - [ ] Windows
- __Mobile__
  - [ ] iOS
  - [ ] Android

## Checklist

> Please tick all of the following boxes that are relevant to your changes.

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or modified tests that prove my changes work as intended
- [x] I have verified that new and existing unit tests pass locally with my changes
- [x] I have verified that my latest changes pass CI workflows for testing and linting
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by nicole-obrien — CHANGES_REQUESTED** [review]
I think this is a good start but we should add a way for the user to view the full details? Maybe a tooltip or something?

**Review by nicole-obrien — CHANGES_REQUESTED** [review]
I think there is two issues still:

- The little triangle of the tooltip is not showing, likely something to do with the scroll bar?
- When hovering over the tooltip, then going back over the text the flag doesn't toggle correctly and then you are left in an inverted state.

Suggestion: We should have the tooltip positioned on top and not right.

**Comment by begonaalvarezd** [comment]
> I think there is two issues still:
> 
> * The little triangle of the tooltip is not showing, likely something to do with the scroll bar?
> * When hovering over the tooltip, then going back over the text the flag doesn't toggle correctly and then you are left in an inverted state.
> 
> Suggestion: We should have the tooltip positioned on top and not right.

@nicole-obrien  I pushed some changed to fix these suggestions

**Review by nicole-obrien — APPROVED** [review]
✅

**Pull request merged**
