### PR TITLE
chore: add mobile specific `PinInput` component with latest tested fixes

### PR DESCRIPTION
**Pull request by amadeu2**
## Summary

This PR uses the latest `PinInput.svelte` component fixed with testers.
We had several issues related to mobile soft keyboards in the past, especially on Android which has several soft keyboard implementations, since each Android phone brand is using their own keyboard apps. Some of them are: Samsung, Huawei, Nokia, Motorola, Sony, LG, HTC, Oppo, Xiaomi, etc.
We also should consider people in Android can install emoji-soft-keyboards which also generate issues.

Please test as many Android soft keyvboards as possible in real phones.

## Changelog

```
- Please write a list of changes
```

### Platforms

> Please select any platforms where your changes have been tested.

-   **Desktop**
    -   [ ] MacOS
    -   [ ] Linux
    -   [ ] Windows
-   **Mobile**
    -   [ ] iOS
    -   [ ] Android

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to **test and verify** that your changes work as intended.

...

## Checklist

> Please tick the following boxes that are relevant to your changes.

-   [ ] I have followed the contribution guidelines for this project
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added or modified tests that prove my changes work as intended
-   [ ] I have verified that new and existing unit tests pass locally with my changes
-   [ ] I have verified that my latest changes pass CI workflows for testing and linting
-   [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by begonaalvarezd — CHANGES_REQUESTED** [review]
I would recomment to update the mobile views that use `PinInput` to use this new component so the PR is complete:

- `packages/mobile/views/login/views/EnterPinView.svelte`
-  `packages/mobile/views/onboarding/views/storage-protection-setup/views/SetupPinProtectionView.svelte`

**Review by begonaalvarezd — COMMENTED** [review]
Additionally, there is a failing test in the CI 🙏🏼

**Comment by amadeu2** [comment]
> I would recomment to update the mobile views that use `PinInput` to use this new component so the PR is complete:
> 
> * `packages/mobile/views/login/views/EnterPinView.svelte`
> * `packages/mobile/views/onboarding/views/storage-protection-setup/views/SetupPinProtectionView.svelte`

Thanks! 😅 I forgot to push them

**Review by begonaalvarezd — APPROVED** [review]
🚀 works great an android
I couldnt test on iOS as I didnt finish my working setup, if we encounter any issue in iOS we can open an issue later on 🙏🏼

**Pull request merged**
