### PR TITLE
feat: initialize firefly theme to `system` by default on every platform

### LINKED ISSUE #3653: [Task]: Set as default `system` theme
### Description

Implement a solution to set as default `system` theme without restart the app.

### Requirements

- [ ] Works on Android
- [ ] Works on iOS

### PR DESCRIPTION
**Pull request by begonaalvarezd**
## Summary

> Please summarize your changes, describing __what__ they are and __why__ they were made.

This PR sets the `appSettings.theme` to `system` the first time the user uses Firefly. 

⚠️ This change affects both **desktop** and **mobile**.

## Changelog

```
- Please write a list of changes
```

## Relevant Issues

> Please list any related issues using [development keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

Close #3653

### Platforms

> Please select any platforms where your changes have been tested.

- __Desktop__
  - [ ] MacOS
  - [x] Linux
  - [ ] Windows
- __Mobile__
  - [x] iOS
  - [x] Android

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to __test and verify__ that your changes work as intended.

...

## Checklist

> Please tick all of the following boxes that are relevant to your changes.

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or modified tests that prove my changes work as intended
- [ ] I have verified that new and existing unit tests pass locally with my changes
- [ ] I have verified that my latest changes pass CI workflows for testing and linting
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by paul-boegelsack — APPROVED** [review]
LGTM 🚀 

Don't know if this is easy to solve and necessary to implement, but when I select system and change the system theme while the app is running, the app theme stays the same.

**Review by amadeu2 — APPROVED** [review]
Works good on iOS too, thanks! 💯
@paul-boegelsack it's needed since we've removed the theme selection screen from on boarding flow, and was required by the UX team by removing that screen. To test it, uninstall previous apps, change your system theme and install again.

**Comment by paul-boegelsack** [comment]
> Works good on iOS too, thanks! 💯 @paul-boegelsack it's needed since we've removed the theme selection screen from on boarding flow, and was required by the UX team by removing that screen. To test it, uninstall previous apps, change your system theme and install again.

@amadeu2 System as default for onboarding is great! I was wondering if it's possible to change the app theme dynamically, when I change the system theme. Currently you have to restart the app like the hint tells you in the settings. But it's not important, I was just curious 😃

**Comment by begonaalvarezd** [comment]
> @amadeu2 System as default for onboarding is great! I was wondering if it's possible to change the app theme dynamically, when I change the system theme. Currently you have to restart the app like the hint tells you in the settings. But it's not important, I was just curious smiley

As I understand it, we would have to monitor the system theme to know when it changed, so i dont know if it its worth it. For now with the hint it should be fine, I dont remember any app updating dynamically without the need to restart.

**Pull request merged**
