### PR TITLE
refactor: backend path alias support

### PR DESCRIPTION
**Pull request by maxwellmattryan**
## Summary
Previously any path alias usage in `backend/`, whether direct or indirectly, would not compile.

### Changelog
```
- Add "@lib" path alias to backend and desktop
- Create specific TS config file for building (fixes path alias usage)
```

## Relevant Issues
- #2377 
 
## Type of Change
- [ ] __Breaking__ - any change that would cause existing functionality to not work as expected
- [x] __Chore__ - refactoring, build scripts or anything else that isn't user-facing
- [ ] __Docs__ - changes to the documentation
- [ ] __Fix__ - a change which fixes an issue
- [ ] __New__ - a change which implements a new feature
- [ ] __Update__ - a change which updates existing functionality

### Platforms
- __Desktop__
	- [ ] MacOS
	- [x] Linux
	- [ ] Windows
- __Mobile__
	- [ ] iOS
	- [ ] Android

### Instructions
The path aliases resolve when used directly in `backend/bindings/node/index.ts` _and_ when used by code that is imported there.

## Checklist
- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added or modified tests that prove my changes work as intended
- [x] I have verified that new and existing unit tests pass locally with my changes
- [x] I have verified that my latest changes pass CI workflows for testing and linting
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by rajivshah3** [comment]
Should this be done on mobile as well?

**Comment by maxwellmattryan** [comment]
> Should this be done on mobile as well?

Yes, we should, but it's not quite symmetrical compared to the NodeJS bindings, namely that `packages/backend/bindings/capacitor` defines the actor handler interface ([here](https://github.com/iotaledger/firefly/blob/develop/packages/backend/bindings/capacitor/src/definitions.ts#L3) - this should really not exist and instead just use the [`IActorHandler`](https://github.com/iotaledger/firefly/blob/develop/packages/shared/lib/typings/bridge.ts#L11)) and `packages/backend/bindings/node` implements functions for that interface ([here](https://github.com/iotaledger/firefly/blob/develop/packages/backend/bindings/node/index.ts)). 

The mobile implementation is in `packages/mobile/capacitor` ([here](https://github.com/iotaledger/firefly/blob/develop/packages/mobile/capacitor/walletPluginApi.ts)). We should refactor this at some point, but it's probably best in a dedicated PR.

**Comment by amadeu2** [comment]
Here's the task previously defined with Nicole to continue with refactor Capacitor bindings plugin
https://github.com/iotaledger/firefly/issues/2337

**Review by nicole-obrien — APPROVED** [review]
Everything builds, and tested by sending a transaction 👍

**Pull request merged**
