### PR TITLE
enhancement: hide pointless activities

### LINKED ISSUE #4648: [Task]: Hide pointless activity where amount = return amount and rest of output is empty
### Task description

People can spam us with basic outputs where the return amount = the amount and there is no native tokens, there is no point claiming it as all the funds are just being sent back to the sender.

### Requirements

- [ ] Do not build activity for this specific case where there is no additional assets in the ouput and the amount = the return amount

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

### PR DESCRIPTION
**Pull request by MarkNerdi**
## Summary
If a transactions amount is the same as the storage deposit return, it will give 0 funds to the user if they claim it.  

## Changelog

```
- dont show activities which contain 0 funds
```

## Relevant Issues
Closes #4648

### Platforms

> Please select any platforms where your changes have been tested.

- __Desktop__
  - [ ] MacOS
  - [ ] Linux
  - [ ] Windows
- __Mobile__
  - [ ] iOS
  - [ ] Android

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to __test and verify__ that your changes work as intended.

...

## Checklist

> Please tick all of the following boxes that are relevant to your changes.

- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or modified tests that prove my changes work as intended
- [ ] I have verified that new and existing unit tests pass locally with my changes
- [ ] I have verified that my latest changes pass CI workflows for testing and linting
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by nicole-obrien — CHANGES_REQUESTED** [review]
You haven't done this check when we receive a new output while logged in?

**Review by nicole-obrien — CHANGES_REQUESTED** [review]
Thinking about this, I think this should be done as a filter that the user can toggle. What do you think?

**Comment by MarkNerdi** [comment]
we could set them to `hidden` and make them visible if we select the `show hidden` filter

**Review by nicole-obrien — CHANGES_REQUESTED** [review]
So currently this is applying to all outputs if they are async, we only want to target the basic outputs that dont have native tokens, as other outputs are inherently an object/asset.

Also we should separate the filter so there is a show valueless activities filter. And a show all hidden filter.

**Review by Tuditi — APPROVED** [review]
LGTM! :fire:

**Pull request merged**
