### PR TITLE
fix: Delete last profile

### LINKED ISSUE #7068: [Task]: Delete last profile crashes
### Task description

There seems to be a race condition deleting and reinicializing the profile manager when deleting the last profile and hitting onboarding right after.
The error thrown is 

```The profile manager was already initialized.```

We might need to wait for the profile manager to be cleared before initializing 

image

### Requirements

Bug fixed

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

### PR DESCRIPTION
**Pull request by brancoder**
## Summary

Destroy profile manager when deleting profile
closes #7068 
...

## Changelog

```
-  add destroyProfileManager() to deleteProfile.ts
```

### Platforms

> Please select any platforms where your changes have been tested.

-   **Desktop**
    -   [ ] MacOS
    -   [x] Linux
    -   [ ] Windows
-   **Mobile**
    -   [ ] iOS
    -   [ ] Android

### Instructions

Delete last remaining profile in the Firefly and user will be redirected to Onboarding flow with profile manager being destroyed in the process

## Checklist

-   [x] I have followed the contribution guidelines for this project
-   [x] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added or modified tests that prove my changes work as intended
-   [x] I have verified that new and existing unit tests pass locally with my changes
-   [x] I have verified that my latest changes pass CI workflows for testing and linting
-   [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by begonaalvarezd — CHANGES_REQUESTED** [review]
Amazing 💪🏼 
Added a comment about a possible improvement 🙏🏼

**Review by begonaalvarezd — CHANGES_REQUESTED** [review]
I wqas testing the code and when I press the button to delete the profile nothing happens 🙏🏼 
image

And if I press it for a second time, there is a crash because it seems llike its trying to delete the profile multiple times

**Review by begonaalvarezd — COMMENTED** [review]
Im thinking we need to add some logic to `packages/desktop/components/popups/ConfirmationPopup.svelte` eg

```
....

export let onConfirm: () => Promise<void> = undefined

.....

    let isBusy = false

    async function onConfirmClick(): Promise<void> {
        isBusy = true
        if (onConfirm) {
            await onConfirm()
        } else {
            closePopup()
        }
        isBusy = false
    }

.....

<popup-buttons class="flex flex-row flex-nowrap w-full space-x-4">
        <Button classes="w-full" outline onClick={onCancelClick}>{localize('actions.cancel')}</Button>
        <Button
            classes="w-full"
            variant={warning || danger ? ButtonVariant.Warning : ButtonVariant.Primary}
            disabled={$selectedAccount.isTransferring || isBusy}
            isBusy={$selectedAccount.isTransferring || isBusy}
            onClick={onConfirmClick}
        >
            {confirmText}
        </Button>
    </popup-buttons>
```
wdyt @brancoder ?

**Comment by brancoder** [comment]
> I wqas testing the code and when I press the button to delete the profile nothing happens 🙏🏼
> And if I press it for a second time, there is a crash because it seems llike its trying to delete the profile multiple times

I cant reproduce these issues with deleting. For me Deleting process is instantaneous :raised_eyebrow: 
We can :pear: test :smiley:

**Review by begonaalvarezd — APPROVED** [review]
🔥

**Pull request merged**
