### PR TITLE
feat: Restore from stronghold

### PR DESCRIPTION
**Pull request by marc2332**
~Depends on https://github.com/iotaledger/firefly/pull/8401~
Closes https://github.com/iotaledger/firefly/issues/7821

### CODE REVIEW

**Comment by marc2332** [comment]
we need https://github.com/iotaledger/firefly/pull/8401 first

**Comment by cpl121** [comment]
Works! 🚀 
When logging in there is a 503 error from the node so I cannot do a complete test, but it correctly restores the wallet 🙌🏼

**Review by marc2332 — COMMENTED** [review]
we need to remove `restoreBackup.ts` as well

**Review by evavirseda — APPROVED** [review]
it's working now :raised_hands:

**Review by cpl121 — APPROVED** [review]

**Pull request merged**
