### PR TITLE
refactor: cleanup `ExpirationDateTimePickerMenu`

### LINKED ISSUE #7245: [Task]: Cleanup `ExpirationTimePickerMenu`

### PR DESCRIPTION
**Pull request by VmMad**
## Summary

I took into account changes to `ExpirationTimePicker` made in #7200 
Fixes #7245 

## Changelog

```
- Remove unnecessary components and simplify the `ExpirationTimePicker` component, that should be a single component imo
```

### Platforms

> Please select any platforms where your changes have been tested.

-   **Desktop**
    -   [ ] MacOS
    -   [x] Linux
    -   [ ] Windows
-   **Mobile**
    -   [ ] iOS
    -   [ ] Android

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to **test and verify** that your changes work as intended.

...

## Checklist

> Please tick the following boxes that are relevant to your changes.

-   [x] I have followed the contribution guidelines for this project
-   [x] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added or modified tests that prove my changes work as intended
-   [ ] I have verified that new and existing unit tests pass locally with my changes
-   [ ] I have verified that my latest changes pass CI workflows for testing and linting
-   [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by cpl121 — APPROVED** [review]
LGTM

**Review by evavirseda — COMMENTED** [review]
the `molecules` folder is going to disappear, so imo you should move the `ExpirationTimePicker` out of it like we did in the other pr :pray:

**Review by evavirseda — APPROVED** [review]
:rocket:

**Review by begonaalvarezd — CHANGES_REQUESTED** [review]
conflicts 🙏🏼

**Review by begonaalvarezd — APPROVED** [review]

**Pull request merged**
