### PR TITLE
fix: quit shortcut

### LINKED ISSUE #2303: [Bug]: Fix shortcut text for quitting application.
### Task description

The dropdown menu in Firefly (Windows and Linux) has the wrong shortcut for quitting the application. The specified text should be changed from Win+Q to Alt+F4 for Windows and from Q to Ctrl+Q for Linux. 

### Requirements

- [x] Change the shortcut text from Win+Q to Alt+F4  in the dropdown menu for Firefly (Windows).
- [x] Change the shortcut text from Q to Ctrl+Q  in the dropdown menu for Firefly (Linux).

### Acceptance criteria

- [x] The shortcut text for quitting on the Windows platform has been changed to Alt+F4.
- [x] The shortcut text for quitting on the Linux platform has been changed to Ctrl+Q.
- [x] The shortcut text for quitting on Mac remains Cmd+Q.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

### PR DESCRIPTION
**Pull request by kraftjs**
## Summary
__Please summarize your changes, describing __what__ they are and __why__ they were made.__
This is an easy fix to get my developer environment up to speed. This PR fixes the Windows and Linux quit shortcut. In Windows it changes the faulty Win+Q shortcut to Alt+F4, and in Linux it changes the shortcut from Q (only worked when menu context was open) to Ctrl+Q (now works from anywhere within Firefly).

### Changelog
```
- Add conditional to account for Windows platform and change shortcut text accordingly.
- Update shortcut for quitting in Linux.
```

## Relevant Issues
Please list any related issues (e.g. bug, task).
Closes #2303 

## Type of Change
Please select any type below that is applicable to your changes, and delete those that are not.
- [x] __Chore__ - refactoring, build scripts or anything else that isn't user-facing
- [x] __Fix__ - a change which fixes an issue

### Platforms
Please select any platforms where your changes have been tested.
- __Desktop__
	- [ ] MacOS
	- [x] Linux
	- [x] Windows
- __Mobile__
	- [ ] iOS
	- [ ] Android

### Instructions
Please describe the specific instructions, configurations, and/or test cases necessary to __test and verify__ that your changes work as intended.

## Checklist
Please tick all of the following boxes that are relevant to your changes, and delete those that are not.
- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have verified that my latest changes pass CI workflows for testing and linting

### CODE REVIEW

**Review by maxwellmattryan — COMMENTED** [review]
The actual change looks good! It's strange that the `yarn.lock` file got included though... might be best to try and exclude that file from this PR.

**Comment by rajivshah3** [comment]
Would this be considered a fix instead of a chore since it's fixing a bug?

**Comment by kraftjs** [comment]
Would this be considered a fix instead of a chore since it's fixing a bug?
```
type:bug: Something isn't working as intended and needs investigating or fixing
type:chore: Housekeeping-like tasks such as modifying dependencies
type:fix: Fix for a bug
```
It seemed like a housekeeping chore to me at first, but now that the changes reach across operating systems it does seem more like a bug fix. I'll change the category type to fix. Do I need to update the commit messages, though?

**Comment by rajivshah3** [comment]
The branch name and commit messages are probably fine, as long as the PR title (since that will become the commit message when this is merged) and labels are changed then everything should be good 👍

**Review by rajivshah3 — APPROVED** [review]

**Pull request merged**
