### PR TITLE
refactor: cleanup component `ProfilePicture`

### LINKED ISSUE #7131: [Task]: Cleanup `ProfilePicture`

### PR DESCRIPTION
**Pull request by VmMad**
## Summary

Fixes #7131
Cleanup component `ProfilePicture`

## Changelog

```
- Cleanup component `ProfilePicture` an rename it to `UserAvatar`
- Add new "Size" enum to use in other components as well
- Cleanup classes and props following coding conventions
```

### Platforms

-   **Desktop**
    -   [ ] MacOS
    -   [x] Linux
    -   [ ] Windows
-   **Mobile**
    -   [ ] iOS
    -   [ ] Android

### Instructions

> ...

## Checklist

-   [x] I have followed the contribution guidelines for this project
-   [x] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added or modified tests that prove my changes work as intended
-   [ ] I have verified that new and existing unit tests pass locally with my changes
-   [ ] I have verified that my latest changes pass CI workflows for testing and linting
-   [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by evavirseda — COMMENTED** [review]
Looks good! just a quick suggestion: would it make sense to rename this component as `Avatar` or `UserAvatar`? wdyt?

**Comment by VmMad** [comment]
> Looks good! just a quick suggestion: would it make sense to rename this component as `Avatar` or `UserAvatar`? wdyt?

That's a nice name!

**Review by evavirseda — APPROVED** [review]
LGTM :rocket:

**Review by begonaalvarezd — APPROVED** [review]
🚀

**Pull request merged**
