### PR TITLE
feat: polish profiles list UI

### LINKED ISSUE #3480: [Subtask]: Fix alignment of profiles within flex box of profile selection page

### PR DESCRIPTION
**Pull request by begonaalvarezd**
## Summary
- improve grid list
- minor css updates for the network tooltip
- update IOTA & shimmer icons

### Changelog
```
feat: polish profiles list UI
```

## Relevant Issues
Closes #3480

## Type of Change
Please select any type below that is applicable to your changes, and delete those that are not.
- [ ] __Breaking__ - any change that would cause existing functionality to not work as expected
- [ ] __Chore__ - refactoring, build scripts or anything else that isn't user-facing
- [ ] __Docs__ - changes to the documentation
- [ ] __Fix__ - a change which fixes an issue
- [ ] __New__ - a change which implements a new feature
- [x] __Update__ - a change which updates existing functionality

### Platforms
Please select any platforms where your changes have been tested.
- __Desktop__
	- [ ] MacOS
	- [x] Linux
	- [ ] Windows
- __Mobile__
	- [ ] iOS
	- [ ] Android

### Instructions
Please describe the specific instructions, configurations, and/or test cases necessary to __test and verify__ that your changes work as intended.

## Checklist
Please tick all of the following boxes that are relevant to your changes, and delete those that are not.
- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or modified tests that prove my changes work as intended
- [ ] I have verified that new and existing unit tests pass locally with my changes
- [ ] I have verified that my latest changes pass CI workflows for testing and linting
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by nicole-obrien — CHANGES_REQUESTED** [review]
Just a few comments:

- The tooltip text style doesn't match design
- The gap between the icon and the tooltip is too big
- The tooltip doesn't move when we scroll

**Comment by kraftjs** [comment]
Following frames are: Figma design, this PR, and stardust-develop
image

The Figma design has a 2px border and that is what this PR has as well, but they don't show similarly in Electron. That's why I previously set the border to 3px, because it matches the white space from the Figma design better.

The Shimmer icon still isn't quite right either, but I was also having trouble with that getting the alignment to match what is in the Figma file.

**Comment by begonaalvarezd** [comment]
> Following frames are: Figma design, this PR, and stardust-develop image
> 
> The Figma design has a 2px border and that is what this PR has as well, but they don't show similarly in Electron. That's why I previously set the border to 3px, because it matches the white space from the Figma design better. One approach that might better match the Figma design is to use the tailwind-css class `ring-2`,
> 
> The Shimmer icon still isn't quite right either, but I was also having trouble with that getting the alignment to match what is in the Figma file.

The figma design doesnt have standarized the network icons, I asked the design team to add the network icons to the UI Kit so they have consistency, but since those icons arent used in figma, it is quite unlikely that we can clone the design. imo as soon as the icons are standarized and look good we should be OK, even though is not an extact copy.

I'll apply some tweaks now to see if I can improve it a bit.
Thanks for the feedback 🙏🏼

**Comment by begonaalvarezd** [comment]
I tried to fix your comments, to me these 2 looks pretty similar 😅 
image
image

🤞🏼

**Review by nicole-obrien — APPROVED** [review]
💯

**Pull request merged**
