### PR TITLE
enhancement: remove trailing spaces on url input

### PR DESCRIPTION
**Pull request by MarkNerdi**
## Summary

> Please summarize your changes, describing **what** they are and **why** they were made.

...

## Changelog

```
- Please write a list of changes
```

### Platforms

> Please select any platforms where your changes have been tested.

-   **Desktop**
    -   [ ] MacOS
    -   [ ] Linux
    -   [ ] Windows
-   **Mobile**
    -   [ ] iOS
    -   [ ] Android

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to **test and verify** that your changes work as intended.

...

## Checklist

> Please tick all of the following boxes that are relevant to your changes.

-   [ ] I have followed the contribution guidelines for this project
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added or modified tests that prove my changes work as intended
-   [ ] I have verified that new and existing unit tests pass locally with my changes
-   [ ] I have verified that my latest changes pass CI workflows for testing and linting
-   [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by JannemanDev** [comment]
I would not strip *all* spaces in an url but only trailing and leading spaces. As a best practise (secutiry wise but also unwanted side effects) you should not change the url if that changes the location.

**Comment by MarkNerdi** [comment]
> I would not strip _all_ spaces in an url but only trailing and leading spaces. As a best practise (secutiry wise but also unwanted side effects) you should not change the url if that changes the location.

it wouldnt really change the location, because a url with spaces is invalid and it would just correct it. 
But i agree that i'm gonna remove this, because its a bit shady if we manipulate the user input, whereas they should check and change it themselves

**Review by Tuditi — COMMENTED** [review]
Maybe we should trim eventID as well?

**Review by Tuditi — APPROVED** [review]
LGTM! :fire:

**Pull request merged**
