### PR TITLE
chore: Clean up imports

### PR DESCRIPTION
**Pull request by marc2332**
Closes https://github.com/iotaledger/firefly/issues/7830

- Convert imports pointing to `shared` to the corresponding `@whatever` path
- Moved subrouters from `packages/desktop` to `packages/shared` so we don't need to use absolute paths when importing routers from `packages/desktop in `packages/shared`
- Converted paths with `../../` pointing to a core module to `@core/whatever`
- Moved some components from `packages/desktop` to `packages/shared` so they can be imported from `packages/shared`

### CODE REVIEW

**Review by evavirseda — COMMENTED** [review]
could also update the `AssetList.svelte`??  :pray: 
 
`import { Filter } from '@components'`

**Comment by marc2332** [comment]
> could also update the `AssetList.svelte`?? 🙏
> 
> `import { Filter } from '@components'`

The problem here is that Filter is a component from `packages/desktop` and AssetList is from `packages/shared`. Currently, there is no way to import in a fancy way things from desktop into shared. Let me see what I can do

**Review by evavirseda — APPROVED** [review]
nice job!!

**Review by begonaalvarezd — APPROVED** [review]
beautiful

**Pull request merged**
