### PR TITLE
fix: Send confirmation expiration time reactivity

### LINKED ISSUE #7096: [Task]: Fix send confirmation expiration time reactivity
### Task description

There seems to be a rectivity issue in the send confirmation flow when displaying the send confirmation popup.
Important to note that the logic is fine, the unlock conditions are correct, is just the popup thats displays it wrong

Repro steps:
1. Lock stroghold (you can lock it from the bottom left profile button, open modal, lock)
2. Prepare a native token or native nft transaction
3. Do not set expiration unlock condition
4. Continue will open the password & enter it
5. The send confirmation is processing and it shows a expiration unlock condition for some reason

Before entering password
image

After entering password
image

### Requirements

Fix expiration unlock condition display in send confirmation popup

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

### PR DESCRIPTION
**Pull request by brancoder**
## Summary

Disable resetting the `initialExpirationDate`  in send confirmation flow if transaction is transferring.
closes #7096 

### Platforms

> Please select any platforms where your changes have been tested.

-   **Desktop**
    -   [ ] MacOS
    -   [x] Linux
    -   [ ] Windows
-   **Mobile**
    -   [ ] iOS
    -   [ ] Android

## Checklist

-   [x] I have followed the contribution guidelines for this project
-   [x] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added or modified tests that prove my changes work as intended
-   [x] I have verified that new and existing unit tests pass locally with my changes
-   [x] I have verified that my latest changes pass CI workflows for testing and linting
-   [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by begonaalvarezd — CHANGES_REQUESTED** [review]
Unfortunetely the fix doesnt work as now it will display `none` for all the transactions even when you set an expiration unlock condition, eg

if i send this 
image
the loading screen will display
image

**Comment by brancoder** [comment]
> Unfortunetely the fix doesnt work as now it will display `none` for all the transactions even when you set an expiration unlock condition, eg

Looks like the issue is in the if clause `if (!initialExpirationDate) {` because initialEcpirationDate can be 0. I don't know if this is intentional to set the Expiration date to one day?

**Review by cpl121 — APPROVED** [review]
Works!

**Review by begonaalvarezd — APPROVED** [review]
🔥

**Pull request merged**
