### PR TITLE
fix: New deep link format

### PR DESCRIPTION
**Pull request by obany**
# Description of change

The original format for deep links can no longer be supported as the host part name of a uri is limited to 63 characters and addresses are 64.

This PR introduces a new format where the `host` part of the url is now a scope for the operation (so in the future we could also support `iota://did/ ` `iota://chat/` etc

The operation being performed is supplied as the first part of the path after the host section.

e.g. `iota://wallet/send/atoi1qzwderym4mesvs7835l52vk7jl7tz264j5yphny8kmeg6xn3vz2w5h67dwl?amt=1000`

In addition there is now an optional `unit` parameter, if not supplied the `amt` is assumed to be `i` units

e.g. `iota://wallet/send/atoi1qzwderym4mesvs7835l52vk7jl7tz264j5yphny8kmeg6xn3vz2w5h67dwl?amt=1.5&unit=Mi`

## Links to any relevant issues

Fixes https://github.com/iotaledger/firefly/issues/884 https://github.com/iotaledger/firefly/issues/700 

## Type of change

- Bug fix (a non-breaking change which fixes an issue)
- Enhancement (a non-breaking change which adds functionality)

## How the change has been tested

Tested on windows, only works in packaged version of the build

## Change checklist

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by adamkundrat** [comment]
Just of interest, the code change seems pretty standard. What's the hold up here? Are there concerns about website injecting "malicious" code within the link?

**Comment by sascha1337** [comment]
passing any value from external possibly requires some solid audits, so that could be the case here.

**Comment by F-Node-Karlsruhe** [comment]
> 
> 
> passing any value from external possibly requires some solid audits, so that could be the case here.

Still, this feature already existed in Trinity, so the security concerns should be sorted out already.
I'd really love to see this PR merged soon :)

**Comment by FlorianWendelborn** [comment]
Additionally, a wallet that can't be used to easily pay for things (or send data in the case of IOTA) is more-or-less worthless for actual usage. As it stands now, Firefly is only good for people not actually wanting to use IOTA to send payments or data.

**Comment by FlorianWendelborn** [comment]
Additionally, a wallet that can't be used to easily pay for things (or send data in the case of IOTA) is more-or-less worthless for actual usage. As it stands now, Firefly is only good for people not actually wanting to use IOTA to send payments or data.

**Comment by adamkundrat** [comment]
> Additionally, a wallet that can't be used to easily pay for things (or send data in the case of IOTA) is more-or-less worthless for actual usage. As it stands now, Firefly is only good for people not actually wanting to use IOTA to send payments or data.

Almost there, see pull: https://github.com/iotaledger/firefly/pull/1244

**Pull request closed without merging**
