### PR TITLE
fix: not visible surplus

### PR DESCRIPTION
**Pull request by jeeanribeiro**
## Summary
Adds visibility of surplus field when conditions are satisfied, the surplus was not showing before

## Changelog

```
- Adds surplus field in BaseActivity type
- Adds surplus field in GenericActivityInformation
- Adds logic to show visible surplus when necessary
```

### Platforms

-   **Desktop**
    -   [ ] MacOS
    -   [x] Linux
    -   [ ] Windows
-   **Mobile**
    -   [ ] iOS
    -   [ ] Android

### Instructions

- Test each deep link with developer tools

#### With native token ID
- [x] should show surplus with 1,000,000 glow & should show storage deposit with 0 glow
`firefly-alpha://wallet/sendConfirmation?address=rms1qpwed3kpaju5rwe4nhplaj3ya6tujzvyuepypya4us95yf2rkp80u5ja230&disableToggleGift=true&disableChangeExpiration=true&amount=1&giftStorageDeposit=true&surplus=1000000&assetId=<NATIVE_TOKEN_ID_THAT_ACCOUNT_IS_HOLDING>`

- [x] should not show surplus & should show storage deposit with 49,600 glow
`firefly-alpha://wallet/sendConfirmation?address=rms1qpwed3kpaju5rwe4nhplaj3ya6tujzvyuepypya4us95yf2rkp80u5ja230&disableToggleGift=true&disableChangeExpiration=true&amount=1&giftStorageDeposit=true&assetId=<NATIVE_TOKEN_ID_THAT_ACCOUNT_IS_HOLDING>`

- [x] should show surplus with 49,000 glow & should show storage deposit with 49,600 glow
`firefly-alpha://wallet/sendConfirmation?address=rms1qpwed3kpaju5rwe4nhplaj3ya6tujzvyuepypya4us95yf2rkp80u5ja230&disableToggleGift=true&disableChangeExpiration=true&amount=1&giftStorageDeposit=true&surplus=49000&assetId=<NATIVE_TOKEN_ID_THAT_ACCOUNT_IS_HOLDING>`

- [x] should show surplus with 60,000 glow & no storage deposit
`firefly-alpha://wallet/sendConfirmation?address=rms1qpwed3kpaju5rwe4nhplaj3ya6tujzvyuepypya4us95yf2rkp80u5ja230&disableToggleGift=true&disableChangeExpiration=true&amount=1&surplus=60000&assetId=<NATIVE_TOKEN_ID_THAT_ACCOUNT_IS_HOLDING>`

#### Without native token ID
- [x] should show surplus not supported error
`firefly-alpha://wallet/sendConfirmation?address=rms1qpwed3kpaju5rwe4nhplaj3ya6tujzvyuepypya4us95yf2rkp80u5ja230&disableToggleGift=true&disableChangeExpiration=true&amount=1&giftStorageDeposit=true&surplus=1000000`

- [x] should not show surplus and should show 42,599 in storage deposit
`firefly-alpha://wallet/sendConfirmation?address=rms1qpwed3kpaju5rwe4nhplaj3ya6tujzvyuepypya4us95yf2rkp80u5ja230&disableToggleGift=true&disableChangeExpiration=true&amount=1&giftStorageDeposit=true`

- [x] should show surplus not supported error
`firefly-alpha://wallet/sendConfirmation?address=rms1qpwed3kpaju5rwe4nhplaj3ya6tujzvyuepypya4us95yf2rkp80u5ja230&disableToggleGift=true&disableChangeExpiration=true&amount=1&giftStorageDeposit=true&surplus=49000`

- [x] should show surplus not supported error
`firefly-alpha://wallet/sendConfirmation?address=rms1qpwed3kpaju5rwe4nhplaj3ya6tujzvyuepypya4us95yf2rkp80u5ja230&disableChangeExpiration=true&amount=1&surplus=50000`

## Checklist

-   [x] I have followed the contribution guidelines for this project
-   [x] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added or modified tests that prove my changes work as intended
-   [x] I have verified that new and existing unit tests pass locally with my changes
-   [x] I have verified that my latest changes pass CI workflows for testing and linting
-   [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by nicole-obrien** [comment]
The second test case is not showing storage deposit, nor is it showing an asset. This leads to the following transaction: https://explorer.shimmer.network/testnet/transaction/0xed58b2af79a2ef81bed56dc41d398e00c4a338497e05003b3a7d7a7eb37a030c
Screenshot 2023-02-27 at 11 34 33

Perhaps the other prs need to be merged first??

**Comment by nicole-obrien** [comment]
Second test case is not showing the storage deposit.

**Comment by maxwellmattryan** [comment]
Only test case 2 is not working now

**Comment by jeeanribeiro** [comment]
@maxwellmattryan @nicole-obrien I'm sorry, I've removed the assetId param from the deep links by mistake, it should test the native tokens, now it should work

**Comment by nicole-obrien** [comment]
Im not sure the expected results of the last test case are actually correct. Lets look at the test cases tomorrow.

**Comment by maxwellmattryan** [comment]
Code looks good and it's working well! Some feedback:
- On the third test case, it only showed 600 glow rather than 49,600. 
- If the storage deposit is zero, then imo we shouldn't show the "Gift storage deposit" key value box in the send confirmation popup. It's interesting because this is happening in the 6th case but in the 4th case it's the opposite.
- Cases 5 and 7 are showing surpluses and 0 for the storage deposits. Case 8 shows the correct storage deposit but it also shows the surplus.

**Review by maxwellmattryan — CHANGES_REQUESTED** [review]
Code looks good. Some feedback:
- On the third test case, it only showed 600 glow rather than 49,600. 
- If the storage deposit is zero, then imo we shouldn't show the "Gift storage deposit" key value box in the send confirmation popup. It's interesting because this is happening in the 6th case but in the 4th case it's the opposite.
- Cases 5 and 7 are showing surpluses and 0 for the storage deposits. Case 8 shows the correct storage deposit but it also shows the surplus.

**Review by maxwellmattryan — APPROVED** [review]
LGTM :fire:

**Pull request merged**
