### PR TITLE
feat: implement android back action

### LINKED ISSUE #2638: [Task]: Handle back button / action on Android
### Task description

Android back button or swipe action are closing the app, where it should go back in the router history.

### Requirements

TBD

### Acceptance criteria

TBD

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

### PR DESCRIPTION
**Pull request by amadeu2**
## Summary

This PR implement android back button action, preventing the app from close asking with a drawer to exit, or formir going back again.

## Changelog

```
- Look commits ;)
```

## Relevant Issues
Closes #2638 

### Platforms

> Please select any platforms where your changes have been tested.

- __Desktop__
  - [ ] MacOS
  - [ ] Linux
  - [ ] Windows
- __Mobile__
  - [ ] iOS
  - [x] Android

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to __test and verify__ that your changes work as intended.

...

## Checklist

> Please tick all of the following boxes that are relevant to your changes.

- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or modified tests that prove my changes work as intended
- [ ] I have verified that new and existing unit tests pass locally with my changes
- [ ] I have verified that my latest changes pass CI workflows for testing and linting
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by paul-boegelsack** [comment]
I have some points about the approach:

- When I close the app through the back button and restart again, it always throws me out after entering the pin. Can you confirm that?
- Can't close the popup through a swipe or with clicking the shaded area
- Maybe it would be better to use the popup to say that the back button action is disabled for now? At least until the first point is fixed?

**Review by paul-boegelsack — APPROVED** [review]

**Comment by amadeu2** [comment]
>     * When I close the app through the back button and restart again, it always throws me out after entering the pin. Can you confirm that?
It's only happens on dev mode, if you execute: `yarn build && NODE_ENV=production yarn android` works without crash.
 
>     * Can't close the popup through a swipe or with clicking the shaded area
yes it should be done better, I could not find a fast way to implement it with the popup, but you right we should allow to close with swipe gesture.

>     * Maybe it would be better to use the popup to say that the back button action is disabled for now? At least until the first point is fixed?

yes why not, what do you suggest? I'm out of ideas 😅

I'll keep it opened to make the changes

**Comment by paul-boegelsack** [comment]
> It's only happens on dev mode, if you execute: yarn build && NODE_ENV=production yarn android works without crash.

Okay, then it is just about closing the popup. Forget about the first and the last point.

> yes why not, what do you suggest? I'm out of ideas 

I would say the solution is a good workaround, I was just worried about the pin crash thing. So maybe you can add the swipe. If that would take too long merge anyway.

**Comment by amadeu2** [comment]
I've double checked and finally could be able to reproduce it, so before the release I hidded the code to exit the app to avoid the crash. I've created a new task to work on the fixes.

**Comment by amadeu2** [comment]
Let's merget it to get the uploaded state.

**Pull request merged**
