### PR TITLE
fix: reactive styling for checkbox text

### LINKED ISSUE #3167: [Task]: Make checkbox settings' text change styling after becoming re-enabled
### Task description

Currently the checkbox settings' text styling does not change after becoming `disabled` - it just stays greyed out until the user re-navigates back to the page.

### Requirements

- [x] Make sure styling of checkbox text changes accordingly when disabling / enabling the setting

### Acceptance criteria

Meets the above requirements.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

### PR DESCRIPTION
**Pull request by maxwellmattryan**
## Summary
Previously, any checkbox text when unchecked then re-checked, the styling does not update accordingly.

### Changelog
```
- Added logic to ensure text colors are updated properly
```

## Relevant Issues
Closes #3167

## Type of Change
- [ ] __Breaking__ - any change that would cause existing functionality to not work as expected
- [ ] __Chore__ - refactoring, build scripts or anything else that isn't user-facing
- [ ] __Docs__ - changes to the documentation
- [x] __Fix__ - a change which fixes an issue
- [ ] __New__ - a change which implements a new feature
- [ ] __Update__ - a change which updates existing functionality

### Platforms
- __Desktop__
	- [ ] MacOS
	- [x] Linux
	- [ ] Windows
- __Mobile__
	- [ ] iOS
	- [ ] Android

### Instructions
Navigate to where there is a checkbox, and check/uncheck it, making sure the colors update accordingly.

## Checklist
- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or modified tests that prove my changes work as intended
- [x] I have verified that new and existing unit tests pass locally with my changes
- [x] I have verified that my latest changes pass CI workflows for testing and linting
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by nicole-obrien — CHANGES_REQUESTED** [review]
I don't think this will work as it will override and custom colour already input etc.

**Comment by nicole-obrien** [comment]
One option would be to do it like this, so that the inputs are not overriden when formatted and then can be used again on each reactive load.
```
<script lang="typescript">
    export let type = TextType.p
    export let fontSize = ''
    export let fontWeight: FontWeightNumber | FontWeightText | '' = ''
    export let lineHeight = ''
    export let secondary = false
    export let disabled = false
    export let highlighted = false
    export let bold = false
    export let smaller = false
    export let bigger = false
    export let error = false
    export let overrideColor = false
    export let color = ''
    export let darkColor = ''
    export let overrideLeading = false
    export let classes = '' // ISSUE: https://github.com/tailwindlabs/tailwindcss/discussions/1446

    const DARKMODE_PREFIX = 'dark:'
    const TEXT_PREFIX = 'text-'
    const LEADING_PREFIX = 'leading-'
    const DEFAULT_TEXT_COLOUR = TEXT_PREFIX + 'gray-800'
    const DEFAULT_TEXT_DARK_COLOUR = DARKMODE_PREFIX + TEXT_PREFIX + 'white'
    const ERROR_TEXT_COLOUR = TEXT_PREFIX + 'red-500'
    const DISABLED_TEXT_COLOUR = TEXT_PREFIX + 'gray-400'
    const DISABLED_TEXT_DARK_COLOUR = TEXT_PREFIX + 'gray-600'
    const HIGHLIGHT_TEXT_COLOUR = TEXT_PREFIX + 'blue-500'
    const SECONDARY_TEXT_COLOUR = TEXT_PREFIX + 'gray-500'

    interface ICustomClass {
        fontWeight: FontWeightNumber | FontWeightText
        color: string
        darkColor: string
        fontSize: string
        lineHeight: string
        wordBreak?: string
        whitespace?: string
        fontFamily?: string
    }

    const DEFAULT_CLASSES_LIST: { [key in TextType]: ICustomClass } = {
        [TextType.h1]: {
            fontWeight: FontWeightText.bold,
            color: DEFAULT_TEXT_COLOUR,
            darkColor: DEFAULT_TEXT_DARK_COLOUR,
            fontSize: 'text-32',
            lineHeight: 'leading-120',
        },
        [TextType.h2]: {
            fontWeight: FontWeightText.bold,
            color: DEFAULT_TEXT_COLOUR,
            darkColor: DEFAULT_TEXT_DARK_COLOUR,
            fontSize: 'text-24',
            lineHeight: 'leading-120',
        },
        [TextType.h3]: {
            fontWeight: FontWeightText.bold,
            color: DEFAULT_TEXT_COLOUR,
            darkColor: DEFAULT_TEXT_DARK_COLOUR,
            fontSize: 'text-18',
            lineHeight: 'leading-140',
        },
        [TextType.h4]: {
            fontWeight: FontWeightText.bold,
            color: DEFAULT_TEXT_COLOUR,
            darkColor: DEFAULT_TEXT_DARK_COLOUR,
            fontSize: 'text-16',
            lineHeight: 'leading-140',
        },
        [TextType.h5]: {
            fontWeight: FontWeightText.bold,
            color: DEFAULT_TEXT_COLOUR,
            darkColor: DEFAULT_TEXT_DARK_COLOUR,
            fontSize: 'text-14',
            lineHeight: 'leading-140',
        },
        [TextType.p]: {
            fontWeight: FontWeightText.normal,
            color: DEFAULT_TEXT_COLOUR,
            darkColor: DEFAULT_TEXT_DARK_COLOUR,
            fontSize: 'text-13',
            lineHeight: 'leading-160',
        },
        [TextType.pre]: {
            fontWeight: FontWeightText.normal,
            color: DEFAULT_TEXT_COLOUR,
            darkColor: DEFAULT_TEXT_DARK_COLOUR,
            fontSize: 'text-12',
            lineHeight: 'leading-140',
            wordBreak: 'break-all',
            whitespace: 'whitespace-pre-line',
            fontFamily: 'font-fira-mono',
        },
    }

    $: formattedFontSize = fontSize ? TEXT_PREFIX + fontSize : ''
    $: formattedLineHeight = lineHeight ? LEADING_PREFIX + lineHeight : ''
    $: formattedColor = color ? TEXT_PREFIX + color : ''
    $: formattedDarkColor = darkColor ? DARKMODE_PREFIX + TEXT_PREFIX + darkColor : ''

    let _fontSize
    let _lineHeight
    let _color
    let _darkColor

    // Format custom inputs
    function setCustomStyles() {
        _fontSize = formattedFontSize
        _lineHeight = formattedLineHeight
        _color = formattedColor
        _darkColor = formattedDarkColor
    }

    // Adjust font for old override classes
    function adjustFont() {
        switch (type) {
            case TextType.p:
                _fontSize = bigger ? 'text-16' : smaller ? 'text-12' : _fontSize
                _lineHeight = bigger ? 'leading-140' : smaller ? 'leading-120' : _lineHeight
                break
            case TextType.pre:
                _fontSize = bigger ? 'text-13' : smaller ? 'text-11' : _fontSize
                break
        }

        fontWeight = bold ? FontWeightText.bold : fontWeight
        _lineHeight = overrideLeading ? '' : _lineHeight
    }

    // Adjust colours for old override classes
    function adjustColor() {
        _color = overrideColor ? '' : _color
        _darkColor = overrideColor ? '' : _darkColor

        if (error) {
            _color = ERROR_TEXT_COLOUR
            _darkColor = ERROR_TEXT_COLOUR
        } else if (disabled) {
            _color = DISABLED_TEXT_COLOUR
            _darkColor = DISABLED_TEXT_DARK_COLOUR
        } else if (highlighted) {
            _color = HIGHLIGHT_TEXT_COLOUR
            _darkColor = HIGHLIGHT_TEXT_COLOUR
        } else if (secondary) {
            _color = SECONDARY_TEXT_COLOUR
            _darkColor = SECONDARY_TEXT_COLOUR
        }
    }
    
    $: $$props, setCustomStyles(), adjustFont(), adjustColor()

    let customClasses: ICustomClass
    $: customClasses = {
        ...DEFAULT_CLASSES_LIST[type],
        ...(_fontSize && { fontSize: _fontSize }),
        ...(fontWeight && { fontWeight }),
        ...(_lineHeight && { lineHeight: _lineHeight }),
        ...((overrideColor || _color) && { color: _color }),
        ...((overrideColor || _darkColor) && { darkColor: _darkColor }),
    }

    $: customClassesString = Object.values(customClasses).join(' ')
</script>

<svelte:element this={type} class={`${customClassesString} ${classes}`} {...$$restProps}>
    <slot />
</svelte:element>```

**Comment by cvarley100** [comment]
What's the status of this?

**Comment by maxwellmattryan** [comment]
> What's the status of this?

This change needs to be made for `stardust-develop` as well, so it should be merged into that branch instead.

**Pull request closed without merging**
