### PR TITLE
feat: validate amount storage deposit before send

### LINKED ISSUE #3592: [Subtask]: Validate amount + storage deposit before send is available
We currently only validate the amount on the send form, but the storage deposit is calculated on the send confirmation screen. We should validate that the total amount that will be sent is available.

### PR DESCRIPTION
**Pull request by jeeanribeiro**
## Summary
Adds amount + storage deposit validation before sending and refactors the expiration time validation code

## Relevant Issues
closes #3592 

### Platforms
- __Desktop__
  - [ ] MacOS
  - [x] Linux
  - [ ] Windows
- __Mobile__
  - [ ] iOS
  - [ ] Android

## Checklist
- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have added or modified tests that prove my changes work as intended
- [x] I have verified that new and existing unit tests pass locally with my changes
- [x] I have verified that my latest changes pass CI workflows for testing and linting
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by MarkNerdi — APPROVED** [review]

**Comment by nicole-obrien** [comment]
The issue has linked properly I think we should always manually link on the right or create the branch through the issue to avoid this problem.

**Review by nicole-obrien — CHANGES_REQUESTED** [review]
I think it is better UX if we don't allow the user to click the send button in the first place, or we add the error message inline to the send confirmation form rather than closing it and showing a notification. This will then allow the user to go back to the previous page and modify their inputs.

**Review by nicole-obrien — CHANGES_REQUESTED** [review]
Currently getting this:
Screenshot 2022-06-28 at 11 54 30

Additionally we need to cover the generic error case or any known error cases from wallet.rs. Right now we just return nothing and show no error message if its not the two validation errors that caused the error.

**Comment by jeeanribeiro** [comment]
> Currently getting this: Screenshot 2022-06-28 at 11 54 30
> 
> Additionally we need to cover the generic error case or any known error cases from wallet.rs. Right now we just return nothing and show no error message if its not the two validation errors that caused the error.

I don't know why this error is showing to you in the console, because the `InsufficientFundsForStorageDepositError` is indeed a constructor

**Review by nicole-obrien — APPROVED** [review]
Made a small changes to validate the send form before the password where possible, and still add error messages to the page if the send fails for another reason 👍

**Pull request merged**
