### PR TITLE
fix: show file picker call is not resolved on iOS

### PR DESCRIPTION
**Pull request by paul-boegelsack**
## Summary

This PR fixes the loading hang on iOS when closing the Stronghold export file picker after changing the password.

## Changelog

```
- Adds a resolve call to the iOS show picker method
```

### Platforms

> Please select any platforms where your changes have been tested.

- __Desktop__
  - [ ] MacOS
  - [ ] Linux
  - [ ] Windows
- __Mobile__
  - [x] iOS
  - [x] Android

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to __test and verify__ that your changes work as intended.

...

## Checklist

> Please tick all of the following boxes that are relevant to your changes.

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or modified tests that prove my changes work as intended
- [ ] I have verified that new and existing unit tests pass locally with my changes
- [ ] I have verified that my latest changes pass CI workflows for testing and linting
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by amadeu2 — COMMENTED** [review]
Seems that this change is avoiding import the Stronghold file 🤔 dont remember well now, there was a function to call from js to allow permissions and show the chooser dialog

**Comment by paul-boegelsack** [comment]
> Seems that this change is avoiding import the Stronghold file 🤔 dont remember well now, there was a function to call from js to allow permissions and show the chooser dialog

Thanks for testing the import, I totally missed that 🙏 I discovered that the picker delegate has some kind of listener method for the cancel button. I moved the resolve into it instead and it seems to work on my side with the exports and imports. Anyway, would be great if you could check again?

**Comment by amadeu2** [comment]
I've checked again and seems the import issue is still there 
Here's the error I got:


to test it I've made a clean build and used this command combo to ensure the pods / plugins are installed avoiding Cocoapods caches:
```bash
cd packages/mobile/ios/App/
rm -rf ~/Library/Caches/CocoaPods Pods ~/Library/Developer/Xcode/DerivedData && pod deintegrate && pod install
```

**Comment by amadeu2** [comment]
I've tested on develop with the same commands and now it's working without any changes! 😅 Sorry I think there was a cache issue too, so we could close it. Thanks for your work! 💫

**Comment by paul-boegelsack** [comment]
> I've tested on develop with the same commands and now it's working without any changes! 😅 Sorry I think there was a cache issue too. Please test it on your side to confirm, thanks!

Works with my devices 👍

**Pull request closed without merging**
