### PR TITLE
chore: update wallet.rs

### PR DESCRIPTION
**Pull request by Tuditi**
## Summary

Update wallet.rs to latest version.

## Changelog

```
- Moved participation to account context
- clearListeners became async
- type changes
```

### Platforms

> Please select any platforms where your changes have been tested.

- __Desktop__
	- [ ] MacOS
	- [x] Linux
	- [ ] Windows
- __Mobile__
	- [ ] iOS
	- [ ] Android

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to __test and verify__ that your changes work as intended.

...

## Checklist

> Please tick all of the following boxes that are relevant to your changes.

- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or modified tests that prove my changes work as intended
- [ ] I have verified that new and existing unit tests pass locally with my changes
- [ ] I have verified that my latest changes pass CI workflows for testing and linting
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by maxwellmattryan — CHANGES_REQUESTED** [review]
Have minor requested changes, looks great otherwise!

**Comment by maxwellmattryan** [comment]
Everything seems to be working as intended, except that I consistently get this error when I try to vote:
```
required input 0x6fc9fe21b2547a92a40276eca35ad34ca50d28122c49dee75d8cb04e8272df840000 is forbidden
```

**Review by nicole-obrien — CHANGES_REQUESTED** [review]
Unable to build locally and on the GH actions

**Review by nicole-obrien — APPROVED** [review]
LGTM!

**Pull request merged**
