### PR TITLE
ui: show available balance and tooltip on the send form

### LINKED ISSUE #4650: [Task]: Show available balance and tooltip on the send form
### Task description

Because the available balance maybe lower than the total balance for an asset. we need to show the available balance on the send form with an explanation for this.
Screenshot 2022-09-22 at 14 33 01

### Requirements

- [x] Use available balance
- [x] Use available balance locale
- [x] Add tooltip for available balance

### Creation checklist

- [x] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

### PR DESCRIPTION
**Pull request by kraftjs**
## Summary

> Please summarize your changes, describing __what__ they are and __why__ they were made.
Because the available balance maybe lower than the total balance for an asset. we need to show the available balance on the send form with an explanation for this.
image

## Changelog

```
- Changed locale string from balance to available balance in send popup
- Added tooltip icon with text to describe available balance
```

## Relevant Issues

> Please list any related issues using [development keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

Closes #4650 

### Platforms

> Please select any platforms where your changes have been tested.

- __Desktop__
  - [x] MacOS
  - [ ] Linux
  - [ ] Windows
- __Mobile__
  - [ ] iOS
  - [ ] Android

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to __test and verify__ that your changes work as intended.

...

## Checklist

> Please tick all of the following boxes that are relevant to your changes.

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or modified tests that prove my changes work as intended
- [ ] I have verified that new and existing unit tests pass locally with my changes
- [ ] I have verified that my latest changes pass CI workflows for testing and linting
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by kraftjs** [comment]
It seems that all the code in the Wallet views are already using `IAsset.balance.available` to display the balance to users (including in the send form - just had to change the locale string to `general.availableBalance`). Should this be changed anywhere?

**Comment by kraftjs** [comment]
Also, any recommendation for a tooltip description of available balance? I'm thinking something along the lines of:
> ##### Available balance
> An asset's total balance minus any funds that are required to cover the storage deposit (i.e. funds that are locked in pending transactions, reserved for Native Tokens, or reserved for NFTs).

**Review by maxwellmattryan — APPROVED** [review]
LGTM :fire:

**Comment by maxwellmattryan** [comment]
> Do we need to show the tooltip and the available balance string for non IOTA and SMR tokens? Can native tokens pay storage deposits or do they have to be paid by the base token?

They have to be paid with the base token

**Pull request merged**
