### PR TITLE
enhancement: adds custom datetime picker

### LINKED ISSUE #3104: [Subtask]: Enhance expiration time picker to allow custom dates
### Task description

TBD

### Requirements

TBD

### Acceptance criteria

TBD

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

### PR DESCRIPTION
**Pull request by jeeanribeiro**
## Summary
Adds custom date-time picker for the expiration date and exports its value

### Changelog
- adds the svelty-picker package to shared package.json

## Relevant Issues
closes #3104

## Type of Change
- [x] __New__ - a change that implements a new feature

### Platforms
- __Desktop__
	- [ ] MacOS
	- [x] Linux
	- [ ] Windows
- __Mobile__
	- [ ] iOS
	- [ ] Android

### Instructions
- Click the `Send` button in the dashboard
- Put the amount in the input
- Select a recipient
- Click `Continue`
- Click on the expiration time
- Click on `Custom date`

## Checklist
- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have verified that new and existing unit tests pass locally with my changes
- [x] I have verified that my latest changes pass CI workflows for testing and linting

### CODE REVIEW

**Review by maxwellmattryan — APPROVED** [review]
Code LGTM!

**Comment by jeeanribeiro** [comment]
> Code LGTM!

Nice! I've added a few more lines to expose the expireDate value, needs some re-reviewing

**Review by MarkNerdi — COMMENTED** [review]
We dont do anything with this value. We somehow need to use it in the trySend-function.

I'm not sure, but do we need to include it in the transferOptions in the sendAmount function in trySend.ts?

Also added a small comment for resetting the expiration time

**Comment by nicole-obrien** [comment]
> We dont do anything with this value. We somehow need to use it in the trySend-function.
> 
> I'm not sure, but do we need to include it in the transferOptions in the sendAmount function in trySend.ts?


Yeah we will use it in the send function, once the correct bindings have been exposed, separate pr though

**Review by nicole-obrien — CHANGES_REQUESTED** [review]
A few issues with functionality:
- Selecting an expiration time, adds a transaction time to the confirmation page as well as the expiration time, and it is equal to the expiration time.
- If a custom date is already selected clicking on the menu item again doesn't open the picker.
- If open clicking on the custom date doesn't close the picker
- The picker lets us choose a time in the past ( We should also add a buffer as we shouldn't allow them to set the expiration time too close to the send time)

I think we can improve the UI/UX by:
- Removing the padding and the x from the top
- Removing the today button
- Adding a confirm and close button at the bottom (confirm should close the menu and the picker, close should only close the picker.
- We also should allow the picker to close when you click the menu beneath it

Screenshot 2022-06-08 at 11 14 53

**Review by nicole-obrien — CHANGES_REQUESTED** [review]
Works and looks a lot better now. I think the padding around the actual picker is a bit off still.
Screenshot 2022-06-12 at 21 28 35

Also I think it might look better in a regular modal similar to the expiration menu itself rather than a tooltip. Maybe one to ask @jvegis

**Review by nicole-obrien — APPROVED** [review]
🏁

**Pull request merged**
