### PR TITLE
Feat: polish ui mobile onboarding

### PR DESCRIPTION
**Pull request by begonaalvarezd**
# Description of change

This PR aims to refine a bit more the onboarding views to prevent unnecessary scrollbars and just make the onboarding views a bit nicer

## Links to any relevant issues

N/A

## Type of change

- Update (a change which updates existing functionality): **UI**

## How the change has been tested

Describe the tests that you ran to verify your changes.

Make sure to provide instructions for the maintainer as well as any relevant configurations.

## Change checklist

Add an `x` to the boxes that are relevant to your changes, and delete any items that are not.

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have checked that my latest changes pass CI tests
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by nicole-obrien — CHANGES_REQUESTED** [review]
Screenshot 2022-01-12 at 21 55 20

Not sure the changes to language selection is very user friendly, it doesn't indicate that this is to select the language and it doesn't indicate the currently selected language.

**Comment by begonaalvarezd** [comment]
> Screenshot 2022-01-12 at 21 55 20
> 
> Not sure the changes to language selection is very user friendly, it doesn't indicate that this is to select the language and it doesn't indicate the currently selected language.

Not sure why the active is not showing up, i'll check that.
About the usability, what do you suggest?

**Comment by begonaalvarezd** [comment]
@nicole-obrien updated active language CSS

**Review by nicole-obrien — APPROVED** [review]
LGTM!

**Pull request merged**
