### PR TITLE
feat: logout on OS lock (macOS & Windows)

### LINKED ISSUE #2037: [Task]: Lock firefly when user locks OS
### Task description

While we do have the auto timeout feature, it would be good to additionally always lock the firefly application when the computers power mode is changed.

### Requirements

- [ ] Logout profile when powermode changes from one classes as active to an unactive one: i.e. sleep, lock, hibernation.

### Acceptance criteria

App locks when power mode changes, app locks on existing timeout too.
Works on Mac and Windows (would be nice in Linux too if possible)

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

### PR DESCRIPTION
**Pull request by cpl121**
Closes #2037 

## Summary

Create an event when the screen is locked from electron and `logout` the profile

## Changelog

```
- Add `lock-screen` event in the main of electron
- Add the event to the `Dashboard`
```

### Platforms

> Please select any platforms where your changes have been tested.

-   **Desktop**
    -   [x] MacOS
    -   [ ] Linux
    -   [ ] Windows
-   **Mobile**
    -   [ ] iOS
    -   [ ] Android

### Instructions

- Start the application and access a profile
- Lock computer screen
- Unlock and check that it has been done correctly on `logout`

## Checklist

> Please tick the following boxes that are relevant to your changes.

-   [x] I have followed the contribution guidelines for this project
-   [x] I have performed a self-review of my own code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added or modified tests that prove my changes work as intended
-   [ ] I have verified that new and existing unit tests pass locally with my changes
-   [x] I have verified that my latest changes pass CI workflows for testing and linting
-   [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by begonaalvarezd** [comment]
@brancoder @msarcev could you please test in windows and macos 🙏🏼 ?

**Review by brancoder — CHANGES_REQUESTED** [review]
On Windows `sleep` event is not captured with `lock-screen` event. We could add `suspend` event for sleep, hibernation and so on.
```
powerMonitor.on('suspend', () => {
    windows.main.webContents.send('lock-screen')
})
```

**Comment by brancoder** [comment]
> Seeing the electron documentation it seems like we could indeed use suspend (though it doesnt say with which OS is compatible) https://www.electronjs.org/docs/latest/api/power-monitor#events there doesnt seem to be other events relevant for us

I have tested the `suspend` event and it works on Windows :+1:

**Review by brancoder — APPROVED** [review]
LGTM

**Pull request merged**
