### PR TITLE
feat: Improve `ExpirationTimePicker` component

### LINKED ISSUE #7710: [Task]: Improve ExpirationTimePicker component
### Task description

Improve `ExpirationTimePicker` component to simplify the "send flow" code related to it.

_Fortunately this component is only used in `SendConfirmationPopup` so we can tailor it to the needs of the "send flow" without affecting other places._

Problems:
- Currently `ExpirationTimePicker` uses an `initialSelected` prop to control the selected value on init, we need to set this if we want the component to show the correct value. But also setting it can change the `expirationDate` which triggers a second `prepareOutput` because of the two-way binding of `expirationDate`.
- There is some "remember previous value" logic in the component that causes bugs. Case found by Branko in the Refactor send flow PR (https://github.com/iotaledger/firefly/pull/7608)
> When sending native tokens toggling gift storage to true sets Expiration time to None if user than clicks to pick new expiration time in the opened time picker last value (in this example In 1 week) is selected instead of No expiration time

Additional info can be fount in the feedback comments of Refactor send flow PR.

### PR DESCRIPTION
**Pull request by evavirseda**
## Summary

Partialy resolves the issue #7710, mainly this part:
>There is some "remember previous value" logic in the component that causes bugs. Case found by Branko in the Refactor send flow PR (https://github.com/iotaledger/firefly/pull/7608)

We can open a new issue for expiration timepicker improvement because it would be  a big refactor 

 Close #7710 

...

## Changelog

```
- Remove unnecessary prop (initialSelected)
- Cleanup code
```

### Platforms

> Please select any platforms where your changes have been tested.

-   **Desktop**
    -   [ ] MacOS
    -   [x] Linux
    -   [ ] Windows

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to **test and verify** that your changes work as intended.

...

## Checklist

> Please tick the following boxes that are relevant to your changes.

-   [ ] I have followed the contribution guidelines for this project
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added or modified tests that prove my changes work as intended
-   [ ] I have verified that new and existing unit tests pass locally with my changes
-   [ ] I have verified that my latest changes pass CI workflows for testing and linting
-   [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by brancoder — CHANGES_REQUESTED** [review]
There are a lot of moving parts in the `ExpirationTimePicker`:
- Toggling `giftStoragDeposit` Button
- Setting Date to expiration time picker initially and also when returning from unlock stronghold popup
- be cautious to not `rebuildTransactionOutput` if not intended by changing expiration date

In regards to this part of the issue:
>There is some "remember previous value" logic in the component that causes bugs. Case found by Branko in the Refactor send flow PR (https://github.com/iotaledger/firefly/pull/7608)

In the original code this can be fix with this change to the `setNull` function:
```
export function setNull(bool: boolean): void {
        if (bool && value) {
            storedValue = value
            value = null
            previouslySelectedPeriod = selectedTimePeriod
            selectedTimePeriod = TimePeriod.None
        } else {
            value = storedValue ?? value
            selectedTimePeriod = previouslySelectedPeriod
        }
    }

```
`setNull` was used when toggling giftStorageDeposit button but it wasn't tracking and resetting all the variables correctly.

**Review by brancoder — APPROVED** [review]
Reverted changes and added a fix for "remember previous value" from this issue https://github.com/iotaledger/firefly/issues/7710

**Comment by evavirseda** [comment]
> Reverted changes and added a fix for "remember previous value" from this issue #7710

LGTM!

**Review by cpl121 — APPROVED** [review]
LGTM

**Review by begonaalvarezd — APPROVED** [review]

**Pull request merged**
